### PR TITLE
Remove onClick callback call in handleClick

### PR DESCRIPTION
**Pull request by Vrq**
With the onClick callback call in handleClick the callback get's triggered twice when the button is clicked: once once for pressed button and second when releasing.

### CODE REVIEW

**Comment by Vrq** [comment]
@mattonit @filipkappa - do you have any comments or questions - or otherwise think that the pull request is fine?

**Comment by anna-morawska** [comment]
Hello Vrg,
thank you for your support, we appreciate this! It's already fixed in the newest version.
Best,
Ania

**Comment by Rotarepmi** [comment]
Your changes have been added.

Because our development procedure does not provide fluent Github commits, I'm closing this pull request.

Many thanks for commiting good solutions!

Best,
Jakub

**Comment by Vrq** [comment]
Thanks

**Pull request closed without merging**
