### PR TITLE
Remove unused moment.js dependency

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@pglejzer @krzysiu-w is it mergable? :)

**Comment by Vrq** [comment]
@pglejzer any comments?

**Comment by pglejzer** [comment]
Hi, I don't work in the mdboostrap anymore. You have to ask another person like @krzysiu-w or @Wojstan about that.

**Comment by Vrq** [comment]
@krzysiu-w what do you think?

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting that, we'll try to remove it in the next release. Before that - we have to check everything in our dev repository :)

**Comment by Vrq** [comment]
@pglejzer  I think you should also remove     "@date-io/moment": "1.3.5" - as it wasn't removed in 5.1.0 yet :)

**Comment by pglejzer** [comment]
@Vrq As I said before, I do not work in mdbootstrap and I don't update this codebase. You have to ask other developers about that.

**Comment by Vrq** [comment]
Sorry, I was meant to mention @krzysiu-w  :)

> I think you should also remove "@date-io/moment": "1.3.5" - as it wasn't removed in 5.1.0 yet :)

**Comment by Vrq** [comment]
@krzysiu-w do you plan to remove it completely, including the "@date-io/moment": "1.3.5"  part? :)

**Comment by krzysiu-w** [comment]
That's my oversight. I didn't notice other libraries are also using the moment as dependency :( Yes, we'll try to remove it completely in the next release :)

**Pull request closed without merging**
