### PR TITLE
Only add modal-open class when the modal is open

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@pglejzer @krzysiu-w what do you think?

**Comment by Vrq** [comment]
@pglejzer any comments?

**Comment by pglejzer** [comment]
Hi, I don't work in the mdboostrap anymore. You have to ask another person like @krzysiu-w or @Wojstan about that.

**Comment by Vrq** [comment]
@Wojstan what do you say?

**Comment by krzysiu-w** [comment]
Hi!

Thanks for your suggestion :) Your solution doesn't work as expected - modal should be opened from the start to add a "modal-open" class to the body. Anyway - I made some corrections (now it will be handled in componentDidUpdate as overflow) and we will add it in the next release (12.07) :)

**Pull request closed without merging**
